### ISSUE TITLE
Suggestion: Markmap formatting

### ISSUE THREAD

**Issue by ramenatorr** [markmap/markmap-vscode#11] opened 2021-01-05 16:20 UTC
I typically start note files from scratch and don't save them until later on. So, for my particular usage, it'd be nice if Markmap didn't need a saved .mm.md file to exist before interpreting it as a Markmap.

I'm not entirely sure of the viability of this, but what could be useful is being able to set the language to markmap in the bottom-right corner as an example. This is similar to setting the language to something like Markdown or JSON. This language interpretation could then trigger the Markmap VS Code extension to run and bring up the preview pane, etc. 

Setting langauge:
![image](https://user-images.githubusercontent.com/50680777/103670159-38412d80-4f47-11eb-961f-60f9c3daf2ca.png)

**Comment by gera2ld** [comment] 2021-01-06 05:18
Sounds like a duplicate of #6

**Comment by gera2ld** [comment] 2024-12-30 07:38
This is already supported.

**Closed by gera2ld** 2024-12-30 07:38 UTC
