### ISSUE TITLE
[Suggestion] ignore the front matter

### ISSUE THREAD

**Issue by fanlushuai** [markmap/markmap-vscode#46] opened 2023-03-07 13:58 UTC
![image](https://user-images.githubusercontent.com/21078607/223442961-48863e46-df9e-41db-8dec-034eb5b3059e.png)

**Comment by gera2ld** [comment] 2023-03-07 14:34
Probably duplicate of #41

**Comment by fanlushuai** [comment] 2023-03-07 14:46
> Probably duplicate of #41

Yes, can it be directly compatible while ignoring the original format of the text

**Comment by fanlushuai** [comment] 2023-03-08 08:07
> Probably duplicate of #41

Right. I think the problem has been fixed. Looking forward to a quick release.

Thank you for your excellent work.

**Closed** 2023-03-10 13:36 UTC
Labels: bug

**Comment by fanlushuai** [comment] 2023-09-02 21:48
> Probably duplicate of #41

The new version 0.1.1 does not fix this issue
